### ISSUE TITLE
Allow ability to list all domains for all users

### ISSUE THREAD

**Issue by hloeung** [canonical/httprequest-lego-provider#67]
### Enhancement Proposal

Hi,

Trying to get a list of all domains for all users, it seems it's not currently possible? `list-domains` requires a `username` and providing `username='*'` returns this error:

`Action id 186 failed: Failed: 'CommandError: User "*" does not exist\n'`

Is there a way to list all domains for all users?

**Comment by mthaddon** [comment]
Fixed in revision 28.
